# Generated by Django 5.2.4 on 2025-08-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_employee_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
