# Generated by Django 5.2.4 on 2025-08-15 14:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import users.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExperimentNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_of_project", models.CharField(max_length=50, unique=True)),
                (
                    "title",
                    models.CharField(
                        max_length=255,
                        verbose_name="Название для PDF/отчётов по эксперименту",
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True, null=True, verbose_name="Особенности эксперимента"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="draft", max_length=16, verbose_name="Статус записи"
                    ),
                ),
                (
                    "version_of_protocol",
                    models.IntegerField(default=1, verbose_name="Версия протокола"),
                ),
                (
                    "latex_started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Начало активации латекса",
                    ),
                ),
                (
                    "latex_completed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Завершение активации латекса",
                    ),
                ),
                (
                    "is_latex_loss",
                    models.BooleanField(
                        default=False,
                        verbose_name="Потери латекса во время ресуспендирования",
                    ),
                ),
                (
                    "optical_density",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="Оптическая плотность реагента",
                    ),
                ),
                (
                    "signal_level",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="Уровень сигнала в реакции",
                    ),
                ),
                (
                    "storage_buffer_ph",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(14.0),
                        ],
                        verbose_name="Значение рН буфера для хранения готового реагента",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="labbook/images",
                        validators=[
                            users.validators.image_validate,
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "png"],
                                "Расширение файла « %(extension)s » не допускается. Разрешенные расширения: %(allowed_extensions)s .",
                                "Недопустимое расширение!",
                            ),
                        ],
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "reminder_date",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Дата напоминания о завершении термостатирования",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        auto_now_add=True, verbose_name="Дата создания отчёта"
                    ),
                ),
                (
                    "updated_at",
                    models.DateField(
                        auto_now=True, verbose_name="Дата последнего изменения"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ответственный за запись об эксперименте",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись об эксперименте",
                "verbose_name_plural": "Записи об эксперименте",
                "ordering": ["owner", "updated_at", "title"],
            },
        ),
    ]
