# Generated by Django 5.2.4 on 2025-08-12 06:58

import django.core.validators
import django.utils.timezone
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExperimentNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_of_project", models.CharField(max_length=50, unique=True)),
                (
                    "title",
                    models.CharField(
                        max_length=255,
                        verbose_name="Название для PDF/отчётов по эксперименту",
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True, null=True, verbose_name="Особенности эксперимента"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="draft", max_length=16, verbose_name="Статус записи"
                    ),
                ),
                ("version_of_protocol", models.IntegerField(default=1)),
                (
                    "latex_started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Начало активации латекса",
                    ),
                ),
                (
                    "latex_completed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Завершение активации латекса",
                    ),
                ),
                (
                    "is_latex_loss",
                    models.BooleanField(
                        default=False,
                        verbose_name="Оценка потери латекса во время ресуспендирования",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="labbook/images",
                        validators=[
                            users.validators.image_validate,
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "png"],
                                "Расширение файла « %(extension)s » не допускается. Разрешенные расширения: %(allowed_extensions)s .",
                                "Недопустимое расширение!",
                            ),
                        ],
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "updated_at",
                    models.DateField(
                        auto_now=True, verbose_name="Дата последнего изменения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись об эксперименте",
                "verbose_name_plural": "Записи об эксперименте",
                "ordering": ["owner", "updated_at", "title"],
            },
        ),
    ]
