# Generated by Django 5.2.4 on 2025-08-15 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labbook", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experimentnote",
            name="optical_density",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(10.0),
                ],
                verbose_name="Оптическая плотность реагента",
            ),
        ),
        migrations.AlterField(
            model_name="experimentnote",
            name="reminder_date",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Дата напоминания о необходимости термостатирования",
            ),
        ),
    ]
