# Generated by Django 5.2.4 on 2025-08-13 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labbook", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="experimentnote",
            name="optical_density",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(10.0),
                ],
                verbose_name="Оптическая плотность",
            ),
        ),
        migrations.AddField(
            model_name="experimentnote",
            name="signal_level",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
                verbose_name="Уровень сигнала в реакции",
            ),
        ),
    ]
