# Generated by Django 5.2.4 on 2025-08-13 12:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labbook", "0003_experimentnote_optical_density_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="experimentnote",
            name="storage_buffer_ph",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(10.0),
                ],
                verbose_name="Значение рН буфера для хранения готового реагента",
            ),
        ),
        migrations.AlterField(
            model_name="experimentnote",
            name="optical_density",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(10.0),
                ],
                verbose_name="Оптическая плотность реагента",
            ),
        ),
    ]
