# Generated by Django 5.2.4 on 2025-08-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labbook", "0004_experimentnote_storage_buffer_ph_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experimentnote",
            name="is_latex_loss",
            field=models.BooleanField(
                default=False, verbose_name="Потери латекса во время ресуспендирования"
            ),
        ),
    ]
