# Generated by Django 5.2.4 on 2025-08-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labbook", "0005_alter_experimentnote_is_latex_loss"),
    ]

    operations = [
        migrations.AddField(
            model_name="experimentnote",
            name="reminder_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата напоминания"
            ),
        ),
    ]
